import { Inter, Oswald, Urbanist } from "next/font/google";
import "@/styles/globals.css";
import { Header, Footer } from "@/components";
import ReduxProvider from "@/provider/redux/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });
const oswald = Oswald({ subsets: ["latin"] });
const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata = {
  title: "Shoe Store | Debraj ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href={oswald.cssUrl} />
        <link rel="stylesheet" href={urbanist.cssUrl} />
      </head>
      <body
        className={`${inter.className} ${oswald.className} ${urbanist.className}`}
      >
        <ReduxProvider>
          <Header />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
